Market/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    
    url(r'create/firm/', views.Create_Firm, name="Create_Firm"),
    url(r'join/firm/', views.Join_Firm, name="Join Firm"),
    url(r'view/firm/', views.View_Firm, name="View_Firm"),
    url(r'leave/firm/', views.Leave_Firm, name="Leave_Firm"),
    url(r'search/stock/', views.Search_Stocks, name = "Search_Stocks"),
    url(r'accounts/profile/', views.Profile, name = "Profile"),
    url(r'api/transaction/', views.Transaction_List.as_view(), name="TransactionList"),
    url(r'api/useraccounts/', views.UserAccounts_API.as_view(), name="UserAccountsList"),
    url(r'api/user/', views.User_API.as_view(), name="UserList"),

    url(r'', views.Home, name="Home"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #for registration settings
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    #my url for app
    url(r'^', include("Market.urls"))

]

Market/models.py
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField

# Create your models here.

#lobby's for user to join to compete
class Firm(models.Model):
    Name = models.CharField(max_length = 200)
    
    def __str__(self):
        return str(self.Name)

#accounts for users to use to play
class UserAccount(models.Model):
    Money = models.FloatField(default=100000.00)
    User = models.ForeignKey(User)
    Firm = models.ForeignKey(Firm, blank=True, null=True)

    def __str__(self):
        return str(self.User.username)

TRANSACTION_TYPES = (
                    ("Buy", "Buy"),
                    ("Sell", "Sell"),
)

#records transaction for each user
class Stock_Transaction(models.Model):
    Ticker = models.CharField(max_length=10)
    Number_of_Shares = models.IntegerField()
    Quote_Each = models.FloatField()
    Total_Cost = models.FloatField()
    Account = models.ForeignKey(UserAccount)
    Type = MultiSelectField(choices=TRANSACTION_TYPES)
    Date_Time = models.DateTimeField(auto_now_add=True)
    Balance_at_Time = models.FloatField()

    def __str__(self):
        # AMZN x20 - EpicTradex
        return "{} *** {} x{} - {}".format(self.Type,self.Ticker, self.Number_of_Shares, self.Account.User.username)

    def check_same_datetime(self, possible_datetime, fields={"Year":0,"Month":1, "Day":2}):
        date_time_list = list(self.Date_Time.timetuple())
        possible_datetime_list = list(possible_datetime.timetuple())
        #loop through all conditions
        for name, index_number in fields.items():
            if date_time_list[index_number] != possible_datetime_list[index_number]:
                return False
        return True


class Stock_Record(models.Model):
    Ticker = models.CharField(max_length=10)
    Number_of_Shares = models.IntegerField()
    Quote_Each = models.FloatField()
    Value = models.FloatField()
    Account = models.ForeignKey(UserAccount)
    Date_Time = models.DateTimeField(auto_now=False, auto_now_add=False)

Market/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from rest_framework import status,generics
from . import services as Market
from . import models
from . import serializer
# Create your views here.

#home page view
def Home(request):
    #important values for rest of function
    user = request.user
                #Cisco    bankAmeri Amazon AT&t Exxon  GenElec ProctorGamble
    headlines = ["CSCO", "BAC", "AMZN", "T", "XOM", "GE", "PG"] 

    return render(request, "Market/index.html", {"user":request.user, "firm":Market.get_firm(request.user)})

@login_required(redirect_field_name='/accounts/login')
def Create_Firm(request):
    #important values for passing to html
    user = request.user
    if request.method == "POST":
        #create new firm
        firm = Market.create_firm(request.POST.get("firm_name"))

        #user joins new firm
        Market.set_firm(user, firm)
        return HttpResponseRedirect("/accounts/profile")
    else:
        return render(request, "Market/firm_form.html",{"user":user, "firm":Market.get_firm(user)})

@login_required(redirect_field_name='/accounts/login')
def Join_Firm(request):
    #important values for passing to html
    user = request.user
    if request.method == "POST":
        #set user's firm to a new firm that they want to join
        Market.set_firm(user, models.Firm.objects.get(Name=request.POST.get("join_firm")))
        return HttpResponseRedirect("/view/firm")
    else:
        return render(request, "Market/firm_list.html", {"user":user,"firms":models.Firm.objects.all(),"firm":Market.get_firm(user)})
@login_required(redirect_field_name='/accounts/login')
def View_Firm(request):

    #important value
    user = request.user
    users_renders = {}
    for i in User.objects.all():
        users_renders[i.id] = str(i.username) 
    return render(request, "Market/firm_view.html", {"user":user,"firm":Market.get_firm(user),"firm_accounts":models.UserAccount.objects.filter(Firm=Market.get_firm(user))})

@login_required(redirect_field_name='/accounts/login')
def Leave_Firm(request):
    #set the users firm to 'No Firm'
    Market.set_firm(request.user, None)
    #redirect to wear user can join a firm
    return HttpResponseRedirect("/join/firm")

@login_required(redirect_field_name='/accounts/login')
def Profile(request):
    #important values for passing to html
    user = request.user
    account = Market.get_UserAccount(user)
    transactions = Market.get_users_transactions(request.user)
    portfolio = models.Stock_Record.objects.filter(Account=account)
    total_portfolio = Market.getTodaysPortfolio(portfolio)
    Market.same_day_condition()

    #if user wants to sell stocks
    if request.method == "POST":
        #get values to conduct transaction
        shares_to_sell = request.POST.get("stock_to_sell")
        stock_row_id = request.POST.get("stock_row_id")
        account = Market.get_UserAccount(user)
        Market.sell_stocks(shares_to_sell, stock_row_id, account)

        return HttpResponseRedirect("/accounts/profile/")
    return render(request,
                 "Market/profile.html", {  
                "user":user, 
                "account":account,
                "firm":Market.get_firm(user),
                "transactions":transactions, 
                "total_portfolio":total_portfolio,
                })
@login_required(redirect_field_name='/accounts/login')
def Search_Stocks(request):
    account = Market.get_UserAccount(request.user)

    if request.method == "POST":
        if request.POST.get("trans_type") == "buy":
            #get html contents needed to enter into db
            number_of_shares = request.POST.get("num_of_shares")
            share_price = request.POST.get("share_price")
            stock_symbol = request.POST.get("stock_symbol").upper()

            Market.buy_stocks(number_of_shares, share_price, stock_symbol, account)

        if request.POST.get("trans_type") == "sell":
            #get html ids needed
            shares_to_sell = request.POST.get("shares_to_sell")
            ticker = request.POST.get("ticker").upper()
            try:
                stock_row = list(models.Stock_Record.objects.filter(Ticker=ticker))[-1]

                print(stock_row.Number_of_Shares)
                print(shares_to_sell)

                if stock_row.Number_of_Shares >= int(shares_to_sell):
                    pass
                else:
                    return render(request, "Market/search_stocks.html", {"account":account, "user":request.user, "firm":Market.get_firm(request.user), "error":"You are selling more stocks than you your last purchase. Use the Profile Page to have an easier time selling your stocks!"})

            except Exception as e:    
                print(e)
                return render(request, "Market/search_stocks.html", {"account":account, "user":request.user, "firm":Market.get_firm(request.user), "error":"You are selling more stocks than you have!"})

            Market.sell_stocks(shares_to_sell, stock_row.id, account)
        
        #redirect to profile page
        return HttpResponseRedirect("/accounts/profile/")


    return render(request, "Market/search_stocks.html", {"account":account, "user":request.user, "firm":Market.get_firm(request.user),})


class Transaction_List(generics.ListCreateAPIView):
    queryset = models.Stock_Transaction.objects.all()
    serializer_class = serializer.Stock_Transaction_API

class UserAccounts_API(generics.ListCreateAPIView):
    queryset = models.UserAccount.objects.all()
    serializer_class = serializer.UserAccount_API

class User_API(generics.ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = serializer.User_API

Market/templates/Market/firm_form.html
{% extends '../base.html' %}

{% block title %} Create Firm{% endblock %} 
{% block content %} 
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Create Firm</h3>
  </div>
  <div class="panel-body">
    <form method="POST" action=".">
        {% csrf_token %}
        <div class="form-group">
            <label for="lobby_name">Firm Name</label>
            <input type="text" class="form-control" name="firm_name" id="lobby_name" placeholder="Best Tradez">
        </div>
        <button type="submit" class="btn btn-success btn-xl">Submit</button>
    </form>
  </div>
</div>


{% endblock %}

Market/templates/Market/firm_list.html
{% extends '../base.html' %}

{% block title %} Join Firm{% endblock %} 
{% block content %}
<div class="alert alert-info" role="alert">
  <a href="/create/firm/" class="alert-link">You can <strong>create your own firm!</strong></a>
</div> 

<h3><u>Firms to Join</u></h3> <p>Firms are lobby's you can join to play against friends and family's. You can view reports to monitor how you are doing and see who is the best trader.</p>
<ul class="list-group">
    {% for firm in firms %}
        <form method="POST" action=".">

        {% csrf_token %}
        <li class="list-group-item">
            
                {{firm}}
                <input type="hidden" name = "join_firm" value="{{firm}}" />
                <div class="pull-right"><button type="submit" class="btn btn-xs btn-success">Join</button></div>
            
        </li>
        </form>
    {% endfor %}
</ul>
{% endblock %}

Market/templates/Market/firm_view.html
{% extends '../base.html' %}

{% block title %} {{firm}} | View{% endblock %} 
{% block content %} 

<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{firm}} Members</h3>
        </div>
        <div class="panel-body">
            <ul class="list-group">
                {% for member in firm.useraccount_set.all %}
                    <li class="list-group-item">{{member}} <div class="pull-right"><span class="badge">${{member.Money}}</span></div></li>
                {% endfor %}
            </ul>
            <div class="alert alert-info" role="alert">
                <a href="/leave/firm/" class="alert-link">If you would like you can <strong>leave this firm</strong></a>
            </div> 
        </div>
    </div>
</div>
<div class="col-md-8">
    <div class="btn-group" role="group" aria-label="...">
        <button type="button" class="btn btn-default" ng-click="getFirmImprovement('Year')" id="yearPercent">Year</button>
        <button type="button" class="btn btn-default" ng-click="getFirmImprovement('Month')" id="monthPercent">Month</button>
        <button type="button" class="btn btn-default" ng-click="getFirmImprovement('Week')" id="weekPercent">Week</button>
    </div>

    <br/>
    <input type="hidden" value="{%for user in firm_accounts%}{{user.id}};{%endfor%}" id="user_accounts_in_firm"/>
    <input type="hidden" value="{{users}}" id="users"/>
    <h3>% Improvement per Member</h3>
    <table class="table table-hover" ng-show='show_firm_table'>
        <thead>
            <tr>    
                <td>Username</td>
                <td>Balance Change</td>
                <td>Current Balance</td>
            </tr>
        </thead>
        <tbody>
            <!--<td>{{ accounts.0 }}</td>-->
            <tr ng-repeat="trader in member_info_to_table | orderBy:'-change' ">
                <td>[[trader.username]]</td>
                <td>[[trader.change]] %</td>
                <td>[[trader.current_balance]]</td>
            </tr>
        <tbody>
    </table>
</div>
{% endblock %}

Market/templates/Market/index.html
{% extends '../base.html' %}

{% block title %}Hermes | Home {% endblock %} 
{% block content %} 
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<h1>Hermes</h1>
<!--<div class="w3-panel w3-card">
    <br>
    <label for="searchFinancialNewsTicker">Search Financial Headlines by Ticker </label>
    <input type="text" placeholder="YHOO" id="searchFinancialNewsTicker"/>
    <br />
    <br />
    <button ng-click="getNewsHeadlines()" class="btn btn-primary">Search</button>
    <br />
    <hr>
    <div ng-show="financial_headlines_show">

    </div>

</div>-->
<br/>

<div class="panel panel-default">
  <div class="panel-heading">Purpose</div>
  <div class="panel-body">
    This is Hermes Exchange. I created Hermes Exchange as a fantasy stock market I wanted when I was learning about the stock market. I hope that this product is easy for you to use and you can have fun learning about how the most complex system humans have ever created works.
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    Firms
  </div>
  <div class="panel-body">
    Firms are lobbies that users can use to see how they are compared to their friends. Firms maybe for learning groups, or may include the most talented traders already in the official market.
  </div>
</div>
<footer>
  <div class="alert alert-warning">Problem? Email us at rohanm02@gmail.com</div>
</footer>
{% endblock %}

Market/templates/Market/profile.html
{% extends '../base.html' %}

{% block title %} {{user}} | Profile {% endblock %} 
{% block content %} 

<input type="hidden" type="hidden" value="{{account.id}}" id="account_num" />
<div class="container-fluid">
    <div class="col-md-2">
        <div class="alert alert-warning" role="alert"><a class="alert-link">Balance <span class="badge">{{account.Money}}</span></a></div>

        <div class="alert alert-danger" role="alert"><a href="/accounts/logout/" class="alert-link"><span class="glyphicon glyphicon-log-out"></span> Logout</a></div>
            {% if firm %}
                <div class="alert alert-info"><span class="glyphicon glyphicon-globe" aria-hidden="true"> </span> View <a class="alert-link" href="/view/firm/">{{firm}}</a></div>

            {% else %}
                <div class="alert alert-info"><span class="glyphicon glyphicon-globe" aria-hidden="true"> </span><a class="alert-link" href="/join/firm/"> Join Firm</a></div>
            {% endif %}
            <div class="alert alert-success" role="alert"><a href="/search/stock/" class="alert-link"><span class="glyphicon glyphicon-usd"></span> Buy Stocks</a></div>
    </div>

    <div class="col-md-10">
       
        <ul class="nav nav-tabs">
        <li role="presentation" id="portfol" ng-click="close_all_profile_tabs(); show_current_portfolio = true; createActiveTab('portfol')" class='active'><a>Current Portfolio</a></li>
        <li role="presentation" id="records" ng-click="close_all_profile_tabs(); show_history=true; createActiveTab('records')"><a>History</a></li>
        <li role="presentation" id="balance" ng-click="close_all_profile_tabs(); show_balance_record = true; createActiveTab('balance')"><a>Balance Record</a></li>
        </ul>
        <br>
        
        <div ng-show = "show_current_portfolio">
            <div ng-show="sell_section == true">
            <div ng-show = "sell_error">
                <label class="label label-danger">You are attempting to sell more stocks than you have!</label>
            </div>
            <form method="POST" action=".">
                {% csrf_token %}
                <label>Number of Stocks to Sell</label>
                <input type="hidden" id="orig_shares_buy"  ng-model="shares_bought">
                <input type="number" ng-change="checkSellParams()" ng-model="shares_to_sell" name="stock_to_sell">
                <input type="hidden" id="row_id" name="stock_row_id">
                <button type="button" id="sell_btn" class="btn btn-danger" data-toggle="modal" data-target="#myModal">Sell</button>
                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Are you sure you would like yo complete your transaction</h4>
                        </div>
                        <div class="modal-body">
                            All sales in this fantasy environment and in the real world are final. Are you sure you would like to sell this stock?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-success">Yes</button>
                        </div>
                        </div>
                    </div>
                </div>
            </form>
                            
                            
             </div>
            <table class="table table-hover table-bordered" id ="stock_search_info">
                <thead>
                    <td>Ticker</td>
                    <td>Last Trade Price</td>   
                    <td>Price Paid</td>
                    <td>% Change</td<>
                    <td>Shares Purchased</td>
                    <td>Purchase Value</td>
                    <td>Day's Purchase Value</td>
                    <td>Transaction Date-Time</td>
                    <td>Sell</td>
                </thead>
                <tbody>
                {% for stock_row in total_portfolio %}

                    <tr>
                            <td><strong>{{ stock_row.Ticker }}</strong></td>
                            <td>${{ stock_row.CurrentPrice }}</td>
                            <td>${{stock_row.Quote_Each}}</td>
                            <td>{{ stock_row.pct_change }}%</td>
                            <td>{{stock_row.Number_of_Shares}}</td>
                            <td>${{ stock_row.Value }}</td>
                            <td>${{ stock_row.Today_Value }}</td>
                            <td>{{ stock_row.Date_Time }}
                            <td style="background-color:#ef432d;" ng-click="showSellSection({{stock_row.Number_of_Shares}}, {{stock_row.id}} )"><p style="color:white" >Sell</p></td>
                            
                            <br>
                        </tr>
                    {%endfor%}

                    
                    </tr>
                </tbody>
                    
            </table>
        </div>
        <div ng-show = "show_history">
            <table class="table table-hover table-bordered" id ="stock_search_info">
            <thead>
                <td>Transaction Type</td>
                <td>Ticker</td>
                <td>Price per Share</td>
                <td>Number of Shares</td>
                <td>Transaction Date-Time</td>
                <td>Total Cost</td>
            </thead>
            <tbody>
                {% for transaction in transactions reversed%}
                <tr {% if transaction.Type.0 == 'Sell' %} style="background-color:#ef432d; text-color:white;"{%else%}style="background-color:#3bfc19"{%endif%}>
                    
                        <td>{{ transaction.Type.0 }}</td>
                        <td>{{ transaction.Ticker }}</td>
                        <td >${{transaction.Quote_Each}}</td>
                        <td >{{transaction.Number_of_Shares}}</td>
                        <td>{{transaction.Date_Time}}</td>
                        <td>${{ transaction.Total_Cost }}</td>
                        
                   
                
                </tr>
                 {%endfor%}
            </tbody>
                    
            </table>
        </div>
        <div ng-show="show_balance_record">
            <div class="btn-group" role="group" aria-label="...">
                <button type="button" class="btn btn-default" ng-click="get_latest_transactions('Year')" id="year">Year</button>
                <button type="button" class="btn btn-default" ng-click="get_latest_transactions('Month')" id="month">Month</button>
                <button type="button" class="btn btn-default" ng-click="get_latest_transactions('Week')" id="week">Week</button>
            </div>

            <div id="graph"><br/>Graph will Appear Here</div>
        </div>

        
    </div>


</div>




{% endblock %}

Market/templates/Market/search_stocks.html
{% extends '../base.html' %}

{% block title %} Search Stocks {% endblock %} 
{% block content %} 
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Stock Search</div>
  <div class="panel-body">
    {% if error %}
        <div class="alert alert-danger">{{error}} </div>
    {% endif %}
    <input type="text"  ng-model="stock_to_search">
    <button ng-click="getStockSearch([[stock_to_search]])" class="btn btn-primary btn-xs">Search</button>

  </div>

  <!-- Table -->
  <div ng-show="showStockInformation" class="container-fluid">
        
        <table class="table table-hover table-bordered" id ="stock_search_info">
            <thead>
                <td>Name</td>
                <td>Last Trade Price</td>
                <td>High</td>
                <td>Low</td>
                <td>Open</td>
                <td>Close</td>
                <td>% Change</td>
            </thead>
            <tbody>
                <tr>
                <td>[[dataStock.Name]]</td>
                <td >[[dataStock.LastTradePriceOnly]]</td>
                <td>[[dataStock.DaysHigh]]</td>
                <td>[[dataStock.DaysLow]]</td>
                <td>[[dataStock.Open]]</td>
                <td>[[dataStock.PreviousClose]]</td>
                <td>[[dataStock.PercentChange]]</td>
                </tr>
            </tbody>
                    
        </table>
        <br>
            <center>Current Account Balance: <span class="badge" ng-model="balance">{{account.Money}}</span></center><br><br>
        <br>
        <div class="col-md-6 w3-panel w3-card" >
            <h2>Buy</h2>
            <hr>
            <div ng-show="showStockInformation" >
            <form method = "POST" action=".">
                {% csrf_token %}
                <input type="hidden" value="buy" name="trans_type">
                # of Shares: <input type="number" name="num_of_shares" id="share_number" ng-model ="share_number" ng-change="searchStockFunc()">
                <input type="hidden" name="share_price" id="share_price" value="[[dataStock.LastTradePriceOnly]]">
                <input type="hidden" id="balance" value="{{account.Money}}">
                <input type="hidden" name="stock_symbol" value="[[stock_to_search]]">
                <div class="pull-right">
                    <span class="label label-info">[[cost]]</span>
                </div>    
                <br><br>
                Estimated Balance: <span class="label label-warning">[[estBalance]]</span><br><br>
    
                <div ng-show="show_error" class="label label-danger">This Purchase Will Put You In Debt</div><br><br>
                <button class= "btn btn-success" type="button" id= "btn_buy" data-toggle="modal" data-target="#buyModal">Buy</button>
                <!-- Modal -->
                <div class="modal fade" id="buyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Are you sure you would like yo complete your transaction</h4>
                        </div>
                        <div class="modal-body">
                            All sales in this fantasy environment and in the real world are final. Are you sure you would like to sell this stock?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-success">Yes</button>
                        </div>
                        </div>
                    </div>
                </div>
            </form>
            </div>
            <br>
        </div>
        <div class="col-md-6 w3-panel w3-card" >
            <h2>Sell</h2>
            <hr>
            <form method = "POST" action=".">
                {% csrf_token %}
                <input type="hidden" name="trans_type" value="sell">
                # of Shares: <input type="number" name="shares_to_sell" id="share_number_sell" ng-model ="share_number_sell" ng-change="sellStockCompute()">
                <input type="hidden" name="ticker" value="[[stock_to_search]]">

                <div class="pull-right">
                    <span class="label label-info">[[dataStock.LastTradePriceOnly * share_number_sell]]</span>
                </div>    
                <br><br>
                Estimated Balance: <span id="sell_bal" class="label label-warning">[[sell_balance]]</span><br><br>
    
                <div ng-show="show_error" class="label label-danger">This Purchase Will Put You In Debt</div><br><br>
                <button class= "btn btn-danger" type="button" id= "btn_sell" data-toggle="modal" data-target="#sellModal" >Sell</button>
                <!-- Modal -->
                <div class="modal fade" id="sellModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Are you sure you would like yo complete your transaction</h4>
                        </div>
                        <div class="modal-body">
                            All sales in this fantasy environment and in the real world are final. Are you sure you would like to sell this stock?
                            <br/>
                            <br/>
                            This sell will delete your last purchase of the stock you searched. If you would like to sell a previous purchase, go to <a href="/accounts/profile/">Profile</a>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-success">Yes</button>
                        </div>
                        </div>
                    </div>
                </div>
            </form>
            <br>
        </div>
        <br>
        <br>
        <br>
    
     </div>
</div>

{% endblock %}